<?php

require_once("guardiankey.class.php");

// Please run "register.php" for generate your configuration
$GKconfig = array(
    'email' => "a@a.com",   /* Admin e-mail */
    'agentid' => "test",  /* ID for the agent (your system) */
    'key' => "",     /* Key in B64 to communicate with GuardianKey */
    'iv' => "",      /* IV in B64 for the key */
    'service' => "",      /* Your service name*/
    'orgid' => "",   /* Your Org identification in GuardianKey */
    'authgroupid' => "", /* A Authentication Group identification, generated by GuardianKey */
    'reverse' => "False", /* If you will locally perform a reverse DNS resolution */
);


$_SERVER['REMOTE_ADDR'] = "1.1.1.1";
$_SERVER['HTTP_USER_AGENT'] = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36";

$GK = new guardiankey($GKconfig);

$usrname = "";
$usremail = $usrname;
$login_failed = 0; // 0 -> success, 1 -> failed. Check in your system
$GKRet        = $GK->checkaccess($usrname,$usremail,$login_failed);
$GKJSONReturn = json_decode($GKRet);

echo $GKRet;
// echo $GKJSONReturn->response == "ACCEPT";


?>
